MATERIAL_NAMES = [
    "epoxidized soybean oil", "epoxidized linseed oil", "epoxidized methyl oleate",
    "epoxidized castor oil", "epoxidized jatropha oil", "epoxidized cottonseed oil",
    "epoxidized canola oil", "epoxidized palm oil", "epoxidized sunflower oil",
    "epoxidized algae oil", "diglycidyl ether of bisphenol A", "diglycidyl ether of resorcinol",
    "glycerol diglycidyl ether", "neopentyl glycol diglycidyl ether", "epichlorohydrin",
    "epoxidized vegetable oil", "succinic acid", "citric acid", "malic acid", "tartaric acid",
    "L-tartaric acid", "sebacic acid", "malonic acid", "glutaric acid", "adipic acid",
    "oxalic acid", "azelaic acid", "itaconic acid", "phthalic acid", "maleic acid",
    "fumaric acid", "vanillic acid", "ferulic acid", "levulinic acid", "ethyl lactate",
    "methyl lactate", "butyl lactate", "ethylene glycol", "diethylene glycol",
    "triethylene glycol", "propylene glycol", "polyethylene glycol", "glycerol",
    "sorbitol", "mannitol", "formic acid", "acetic acid", "lactic acid", "stearic acid",
    "oleic acid", "linoleic acid", "palmitic acid", "lauric acid", "decanoic acid",
    "acrylic acid", "methacrylic acid", "trimellitic anhydride", "hexahydrophthalic anhydride",
    "phthalic anhydride", "maleic anhydride", "succinic anhydride", "dicyandiamide",
    "imidazole", "benzimidazole", "zinc acetate", "calcium hydroxide", "magnesium oxide",
    "aluminum oxide", "silicon dioxide", "carbon black", "graphene oxide", "nanoclay",
    "montmorillonite", "kaolinite", "halloysite nanotubes", "silane coupling agent",
    "triethoxysilane", "aminopropyltriethoxysilane", "dimethylformamide", "dimethyl sulfoxide",
    "tetrahydrofuran", "chloroform", "acetone", "toluene", "xylene", "hexane", "cyclohexane",
    "methanol", "ethanol", "butanol", "acetonitrile", "benzene", "phenol", "resorcinol",
    "urea", "melamine", "formaldehyde", "polyethyleneimine", "polyvinyl alcohol", "polycaprolactone",
    "polypropylene glycol", "polylactic acid", "polyhydroxyalkanoate", "polybutylene succinate",
    "polyethylene terephthalate", "polytrimethylene terephthalate", "polybutylene adipate",
    "polycarbonate", "polyether ether ketone", "polyphenylene sulfide", "polystyrene",
    "polyurethane", "polyacrylonitrile", "polyvinyl chloride", "polyvinylidene fluoride",
    "thermoplastic polyurethane", "thermoset epoxy", "bioepoxy resin", "biobased epoxy resin",
    "resorcinol diglycidyl ether", "vanillin diglycidyl ether", "eugenol epoxy", "cardanol epoxy",
    "epoxidized cardanol", "epoxidized eugenol", "epoxidized vanillin", "epoxidized isoeugenol",
    "furfuryl alcohol", "hydroxymethylfurfural", "epoxidized limonene", "epoxidized linoleic acid",
    "glycidyl methacrylate", "epoxidized soybean methyl ester", "methylenedianiline",
    "triethylenetetramine", "diethylenetriamine", "hexamethylenediamine", "isophorone diamine",
    "aromatic amine hardener", "aliphatic amine hardener", "anhydride hardener", "cycloaliphatic epoxy",
    "novolac epoxy resin", "tung oil", "linseed oil", "castor oil", "hemp seed oil", "jojoba oil",
    "karanja oil", "neem oil", "rapeseed oil", "palm kernel oil", "camelina oil", "rice bran oil",
    "cottonseed oil", "corn oil", "algae-based oil", "microalgae oil", "glycerol carbonate",
    "carbon nanotubes", "nanocellulose", "cellulose nanocrystals", "cellulose nanofibrils",
    "lignin", "tannin", "chitosan", "gelatin", "alginate", "pectin", "zein", "silk fibroin",
    "keratin", "guar gum", "xanthan gum", "starch", "amylose", "amylopectin", "dextran",
    "polyaspartic acid", "polyglutamic acid", "poly(ethylene oxide)", "poly(propylene oxide)",
    "silica nanoparticles", "titanium dioxide", "zinc oxide", "barium sulfate", "calcium carbonate",
    "strontium carbonate", "bentonite", "magnetite", "iron oxide", "ferric chloride", "cobalt acetate",
    "manganese dioxide", "nickel nitrate", "silver nitrate", "gold nanoparticles", "platinum nanoparticles",
    "tin oxide", "zinc stearate", "calcium stearate", "copper sulfate", "boric acid", "boron trifluoride etherate",
    "dibutyltin dilaurate", "tin(II) 2-ethylhexanoate",
    "cobalt naphthenate", "zinc naphthenate", "methyl ethyl ketone peroxide",
    "benzoyl peroxide", "tert-butyl hydroperoxide", "cumene hydroperoxide",
    "azobisisobutyronitrile", "2,2'-azobis(2-methylpropionitrile)", "potassium persulfate",
    "ammonium persulfate", "sodium persulfate", "benzoin", "benzil", "triallyl isocyanurate",
    "triallyl cyanurate", "trimethylolpropane", "pentaerythritol", "sorbitan monooleate",
    "dioctyl phthalate", "dibutyl phthalate", "dimethyl phthalate", "triacetin",
    "tributyl citrate", "acetyl tributyl citrate", "triethyl citrate", "acetyl triethyl citrate",
    "epoxidized esters of soybean oil", "phosphoric acid", "boron oxide", "aluminum phosphate",
    "ammonium polyphosphate", "triphenyl phosphate", "dimethyl methylphosphonate",
    "resorcinol phosphate", "melamine phosphate", "melamine cyanurate", "melamine polyphosphate",
    "urea phosphate", "cyanuric acid", "dicyandiamide phosphate", "sodium hexametaphosphate",
    "calcium phosphate", "tris(2-chloroethyl) phosphate", "tris(1,3-dichloro-2-propyl) phosphate",
    "trichloropropyl phosphate", "silicone oil", "PDMS", "perfluoropolyether",
    "ethylene propylene diene monomer", "styrene-butadiene rubber", "nitrile rubber",
    "chloroprene rubber", "natural rubber", "epoxidized natural rubber", "butyl rubber",
    "ethylene vinyl acetate", "polyvinylpyrrolidone", "polyacrylamide", "acrylamide",
    "acrylonitrile", "methyl acrylate", "butyl acrylate", "ethyl acrylate",
    "methyl methacrylate", "butyl methacrylate", "hydroxyethyl methacrylate",
    "glycidyl acrylate", "vinyl acetate", "vinyl chloride", "vinylidene chloride",
    "vinyl alcohol", "vinyl butyral", "maleic anhydride copolymer", "styrene maleic anhydride",
    "styrene acrylonitrile", "styrene butadiene", "ethylene maleic anhydride",
    "maleimide", "bismaleimide", "epoxy novolac", "epoxy phenol novolac",
    "hydantoin", "isocyanuric acid", "oxazoline", "oxirane", "glyoxal",
    "glutaraldehyde", "formic aldehyde", "terephthalic acid", "isophthalic acid",
    "dimethyl terephthalate", "dimethyl phthalate", "dimethyl isophthalate", "bisphenol A",
    "bisphenol F", "bisphenol S", "cyclohexanedimethanol", "1,4-butanediol", "1,6-hexanediol", "ethylene diamine",
    "1,2-diaminopropane", "1,3-diaminopropane", "1,4-diaminobutane",
    "1,6-diaminohexane", "isophorone diisocyanate", "methylene diphenyl diisocyanate",
    "toluene diisocyanate", "hexamethylene diisocyanate", "lysine", "arginine", "histidine",
    "cysteine", "methionine", "glutamine", "glutamic acid", "aspartic acid", "serine",
    "threonine", "tyrosine", "gelatin hydrolysate", "keratin hydrolysate", "casein",
    "lignosulfonate", "alkali lignin", "organosolv lignin", "humic acid", "fulvic acid",
    "bitumen", "asphalt", "biochar", "activated carbon", "graphitic carbon", "reduced graphene oxide",
    "fullerene", "carbon nanotube", "diamond nanoparticle", "boron nitride", "alumina",
    "magnesia", "silicon carbide", "calcium silicate", "aluminum silicate", "talc",
    "mica", "vermiculite", "perlite", "diatomaceous earth", "zeolite", "hydroxyapatite",
    "calcium hydroxide", "magnesium hydroxide", "barium hydroxide", "zinc hydroxide",
    "sodium hydroxide", "potassium hydroxide", "sodium carbonate", "potassium carbonate",
    "calcium carbonate", "magnesium carbonate", "sodium bicarbonate", "ammonium bicarbonate",
    "calcium chloride", "magnesium chloride", "sodium chloride", "potassium chloride",
    "aluminum chloride", "ferric chloride", "ferrous sulfate", "zinc sulfate", "copper sulfate",
    "cobalt sulfate", "nickel sulfate", "chromium sulfate", "manganese sulfate", "lead nitrate",
    "silver nitrate", "gold chloride", "platinum chloride", "tin chloride", "stannous chloride",
    "boric acid", "tannic acid", "gallic acid", "quercetin", "luteolin", "genistein",
    "curcumin", "resveratrol", "catechin", "epicatechin", "theobromine", "caffeine",
    "nicotine", "saponin", "terpene", "limonene", "camphor", "menthol", "eucalyptol", "thymol", "carvacrol", "eugenol",
    "isoeugenol", "guaiacol", "anisole", "safrole",
    "myrcene", "farnesene", "nerol", "citral", "geraniol", "linalool", "borneol",
    "pinene", "beta-caryophyllene", "camphene", "limonene oxide", "menthone",
    "perillyl alcohol", "benzyl alcohol", "cinnamyl alcohol", "salicyl alcohol",
    "benzaldehyde", "vanillin", "anisaldehyde", "cinnamaldehyde", "cuminaldehyde",
    "furfural", "hydroxymethylfurfural", "levulinic ketal", "levulinic ester",
    "gamma-valerolactone", "delta-valerolactone", "butyrolactone", "caprolactone",
    "lactide", "glycolide", "1,3-propanediol", "1,2-propanediol", "1,4-butanediol diglycidyl ether",
    "sorbitol diglycidyl ether", "glycerol triglycidyl ether", "epoxidized tall oil",
    "epoxidized linoleic acid methyl ester", "bio-based alkyd resin", "rosin ester",
    "rosin acid", "abietic acid", "dehydroabietic acid", "levopimaric acid",
    "hydrogenated rosin", "gum rosin", "maleated rosin", "fumarated rosin",
    "rosin-based polyol", "rosin amine", "rosin acrylate", "castor oil based polyol",
    "monoglyceride of castor oil", "ricinoleic acid", "acetylated castor oil",
    "hydrogenated castor oil", "12-hydroxystearic acid", "2-ethylhexanoic acid",
    "capric acid", "caprylic acid", "lauryl alcohol", "stearyl alcohol", "cetyl alcohol",
    "hexanol", "octanol", "decanol", "isononyl alcohol", "tridecyl alcohol", "isoamyl alcohol",
    "tripropylene glycol", "tetrapropylene glycol", "isopropyl alcohol", "tert-butyl alcohol",
    "methyl isobutyl ketone", "diisobutyl ketone", "acetophenone", "benzophenone",
    "dibenzoyl peroxide", "dimethyl carbonate", "diethyl carbonate", "propylene carbonate",
    "ethyl methyl carbonate", "butylene carbonate", "glycerol carbonate", "choline chloride",
    "ethanolamine", "diethanolamine", "triethanolamine", "ethylenediaminetetraacetic acid",
    "nitrilotriacetic acid", "oxalic acid dihydrate", "citric acid monohydrate", "tartaric acid dihydrate", "imidazolium chloride", "1-butyl-3-methylimidazolium hexafluorophosphate",
    "1-ethyl-3-methylimidazolium acetate", "choline bicarbonate", "methyltrioctylammonium chloride",
    "tetraethylammonium bromide", "tetraethylammonium hydroxide", "benzyltriethylammonium chloride",
    "hexadecyltrimethylammonium bromide", "tetramethylammonium chloride", "tetraethylphosphonium chloride",
    "triphenylphosphine oxide", "phosphonium ionic liquid", "zinc chloride", "zinc borate",
    "sodium borohydride", "sodium hypophosphite", "potassium permanganate", "calcium nitrate",
    "copper acetate", "manganese acetate", "vanadium pentoxide", "chromium trioxide",
    "tin oxide nanoparticles", "zirconium oxide", "cerium oxide", "yttrium oxide",
    "bismuth oxide", "tungsten oxide", "molybdenum trioxide", "ruthenium chloride",
    "palladium acetate", "palladium chloride", "rhodium chloride", "lanthanum nitrate",
    "neodymium chloride", "samarium nitrate", "gadolinium oxide", "europium nitrate",
    "terbium chloride", "erbium oxide", "dysprosium nitrate", "scandium nitrate",
    "oleic acid", "linolenic acid", "elaidic acid", "arachidic acid", "behenic acid",
    "gondoic acid", "erucic acid", "nerolic acid", "petroselinic acid", "heneicosylic acid",
    "triacontanoic acid", "cerotic acid", "carnauba wax", "beeswax", "paraffin wax",
    "candelilla wax", "lanolin", "ozokerite", "microcrystalline wax", "montan wax",
    "soy wax", "jojoba wax", "hydrogenated vegetable oil", "castor wax", "stearin",
    "glyceride", "diglyceride", "monostearin", "tripalmitin", "tristearin", "trilinolein",
    "glyceryl stearate", "glyceryl oleate", "glyceryl linoleate", "glyceryl palmitate",
    "palmityl alcohol", "cetylic alcohol", "isostearyl alcohol", "octyldodecanol",
    "caprylyl glycol", "hexylene glycol", "pentylene glycol", "neopentyl glycol",
    "trimethylolpropane triacrylate", "dipentaerythritol pentaacrylate", "bisphenol A diglycidyl ether dimethacrylate",
    "urethane dimethacrylate", "polyether polyol", "polysiloxane", "polyhedral oligomeric silsesquioxane",
    "resorcinol formaldehyde resin", "melamine formaldehyde resin", "urea formaldehyde resin",
    "phenol formaldehyde resin", "benzoxazine resin", "acrylonitrile butadiene styrene",
    "polyphenylene oxide", "sodium lignosulfonate", "kraft lignin", "catechol", "pyrogallol", "furfurylamine", "5-hydroxymethylfurfural acetate", "sorbitol acrylate", "xylitol diacrylate",
    "mannitol triacrylate", "itaconic acid dimethyl ester", "muconic acid", "levoglucosenone",
    "isosorbide", "isosorbide dimethacrylate", "isosorbide diacrylate", "erythritol tetranitrate",
    "erythritol triacrylate", "ribitol", "arabinitol", "polyfurfuryl alcohol", "polyhydroxybutyrate",
    "polyhydroxyvalerate", "poly(limonene carbonate)", "poly(ethylene furanoate)", "poly(propylene fumarate)",
    "maleated starch", "citric acid polyester", "cellulose acetate", "cellulose propionate",
    "cellulose butyrate", "carboxymethyl cellulose", "hydroxyethyl cellulose", "hydroxypropyl cellulose",
    "ethyl cellulose", "methacrylated cellulose", "alginate sodium salt", "calcium alginate",
    "pectin methyl ester", "gelatin methacryloyl", "silk sericin", "silk fibroin hydrogel",
    "chitin", "chitin nanofibers", "crab shell chitosan", "fungal chitosan", "marine collagen",
    "hydrolyzed collagen", "elastin", "tropoelastin", "keratin peptide", "feather keratin",
    "soy protein isolate", "wheat gluten", "zein protein", "pea protein", "caseinate", "albumin",
    "fibrin", "fibrinogen", "myosin", "actin", "spidroin", "microcrystalline cellulose",
    "nanofibrillated cellulose", "cellulose nanowhiskers", "TEMPO-oxidized cellulose",
    "oxidized starch", "crosslinked dextran", "dextran methacrylate", "pullulan", "pullulan acetate",
    "xanthan gum", "gellan gum", "locust bean gum", "guar gum derivative", "acacia gum",
    "tragacanth gum", "beta-cyclodextrin", "hydroxypropyl-beta-cyclodextrin", "alpha-cyclodextrin",
    "gamma-cyclodextrin", "cyclodextrin polymer", "poly(ethylene-co-maleic anhydride)",
    "poly(ethylene-co-glycidyl methacrylate)", "poly(maleic anhydride-alt-1-octadecene)",
    "poly(itaconic anhydride)", "poly(acrylic acid-co-acrylamide)", "poly(2-hydroxyethyl methacrylate)",
    "poly(2-ethyl-2-oxazoline)", "poly(N-isopropylacrylamide)", "poly(vinylpyrrolidone-co-vinyl acetate)",
    "poly(acrylamide-co-acrylic acid)", "poly(acrylonitrile-co-butadiene)", "poly(sodium acrylate)",
    "polyacrylic superabsorbent", "starch-g-polyacrylic acid", "starch-g-polyacrylamide",
    "gelatin-g-polyacrylic acid", "lignin-g-polyacrylamide", "chitosan-g-polyacrylamide",
    "poly(siloxane-urethane)", "poly(siloxane-acrylate)", "poly(siloxane-epoxy)", "silicone urethane",
    "epoxidized siloxane", "fluorinated siloxane", "polyfluorinated alcohol", "perfluorodecanoic acid",
    "trifluoroethanol", "hexafluoroisopropanol", "fluoropolyether", "fluorinated acrylic monomer",
    "hexafluorobutyl methacrylate", "fluorinated diacrylate", "silane-grafted polyolefin",
    "vinyltrimethoxysilane", "methacryloxypropyltrimethoxysilane", "3-aminopropyltriethoxysilane",
    "vinyltriethoxysilane", "epoxy-functional silane", "glycidyltrimethoxysilane",
    "isocyanatoethyl methacrylate", "2-isocyanatoethyl acrylate", "4-isocyanatobenzyl methacrylate",
    "urethane acrylate oligomer", "aliphatic urethane acrylate", "aromatic urethane acrylate",
    "hexanediol diacrylate", "triethylene glycol dimethacrylate", "poly(ethylene glycol) diacrylate",
    "poly(propylene glycol) dimethacrylate", "neopentyl glycol diacrylate", "pentaerythritol tetraacrylate",
    "dipentaerythritol hexaacrylate", "trimethylolpropane trimethacrylate", "isobornyl acrylate",
    "lauryl acrylate", "stearyl methacrylate", "butyl methacrylate", "ethylhexyl acrylate",
    "benzyl acrylate", "glycidyl methacrylate", "maleimide acrylate", "benzophenone acrylate",
    "thioxanthone acrylate", "benzoin ethyl ether", "benzoin isobutyl ether", "benzil dimethyl ketal",
    "camphorquinone", "2,4,6-trimethylbenzoyldiphenylphosphine oxide", "acylphosphine oxide",
    "1-hydroxycyclohexyl phenyl ketone", "diphenyl(2,4,6-trimethylbenzoyl)phosphine oxide",
    "titanocene", "ferrocene-based photoinitiator", "silane-based photoinitiator", "amine synergist",
    "ethyl 4-dimethylaminobenzoate", "methyl diethanolamine", "benzyl dimethyl ketal",
    "alkylated urea", "melamine derivative", "benzoguanamine", "acryloyl chloride", "methacryloyl chloride",
    "epichlorohydrin methacrylate", "epoxy-functional acrylate", "cyanate ester", "difunctional epoxy silane",
    "methacrylated lignin", "allyl lignin", "tannin acrylate", "tannin epoxy", "furan-based epoxy",
    "bisfuran epoxy", "furanone", "pyrone", "maleimide-functional lignin", "biobased cyanate ester",
    "imidazole-functional epoxy", "dicyandiamide-modified urea", "triazine-based crosslinker",
    "polycarbodiimide", "polyaziridine", "aziridine crosslinker", "polyoxazoline", "polyurea",
    "polycarbamate", "biuret", "uretdione", "isocyanurate", "allophanate", "oxazolidone",
    "carbamate-modified silane", "carbodiimide hardener", "polyphosphazene", "polyphosphate",
    "trisilanol phenyl silsesquioxane", "epoxy-functional polyhedral silsesquioxane",
    "graphene nanoplatelets", "carbon fiber powder", "conductive carbon black", "silver nanowire",
    "copper nanowire", "aluminum powder", "boron carbide", "zinc ferrite", "iron silicide",
    "barium titanate", "strontium titanate", "calcium titanate", "lead zirconate titanate",
    "lithium niobate", "lanthanum manganite", "yttrium barium copper oxide", "indium tin oxide",
    "aluminum doped zinc oxide", "fluorine doped tin oxide", "reduced graphene oxide hybrid",
    "carbon nanotube-grafted silica", "halloysite-polymer hybrid", "organoclay", "polymer-intercalated clay",
    "biobased organoclay", "cyclodextrin inclusion complex", "polyrotaxane", "supramolecular polymer",
    "dynamic covalent network", "vitreous silica", "borosilicate", "borophene", "MXene",
    "nanodiamond", "nanodiamond-polymer composite", "graphdiyne", "phosphorene", "tungsten disulfide"
]
