# Generates templates for polymer property extraction tasks.

SENTENCE_TEMPLATES = [
    # Original 100 templates (revised slightly for consistency)
    "The {property} ({symbol}) of {polymer} was measured to be {value} {unit}.",
    "{polymer} showed a {property} of approximately {value} {unit}.",
    "According to the analysis, {symbol} ≈ {value} {unit} for {polymer}.",
    "{property} was evaluated at around {value}{unit} in the case of {polymer}.",
    "After processing, {polymer} exhibited a {property} value of {value} {unit}.",
    "A peak {property} of {value}{unit} was recorded in {polymer} using standard tests.",
    "The value of {symbol} for {polymer} is near {value}{unit}, based on experimental data.",
    "Under thermal cycling, {polymer}'s {property} reached {value} {unit}.",
    "At {value}{unit}, a transition attributed to {property} occurred in {polymer}.",
    "Observed data place the {property} ({symbol}) of {polymer} at approximately {value}{unit}.",
    "Measurements indicate a {property} of {value} {unit} for the tested {polymer}.",
    "{symbol} for {polymer} was found at {value} {unit}, confirming prior findings.",
    "Experimental results show {polymer} to possess a {property} of {value} {unit}.",
    "A {value}{unit} value was observed, potentially corresponding to {property} in {polymer}.",
    "Typical measurements for {polymer} yield a {symbol} near {value}{unit}.",
    "The test detected {symbol} = {value} {unit}, relevant to {polymer}'s {property}.",
    "{polymer} exhibited an abnormal {property}, estimated around {value} {unit}.",
    "No {property} was directly recorded, but {symbol} reached {value}{unit} in {polymer}.",
    "Interestingly, the {symbol} response in {polymer} indicated a value of {value} {unit}.",
    "Although indirect, {polymer} was inferred to have a {property} of {value}{unit}.",
    "Both the {property} and the {symbol} of {polymer} were measured as {value} and {value} {unit}, respectively.",
    "The material exhibited a {property} of {value}{unit} and a secondary {property} around {value}{unit}.",
    "While measuring {polymer}, a shift at {value} {unit} indicated the {property}.",
    "From DSC results, {symbol} ≈ {value}{unit} was extracted for {polymer}.",
    "{polymer} presents a {property} ranging between {value} and {value} {unit}.",
    "A secondary peak in {polymer}'s behavior was linked to a {property} near {value} {unit}.",
    "At approximately {value}{unit}, {polymer} underwent a significant {property} change.",
    "The {property} of {polymer} was deduced from the curve onset at {value} {unit}.",
    "{symbol} showed fluctuation between {value}–{value} {unit}, highlighting material instability.",
    "The {symbol} associated with {polymer} peaked around {value}{unit}.",
    "{property} and {symbol} were both confirmed in {polymer} at {value}{unit}.",
    "{polymer} had a baseline {property} of {value} {unit}, consistent across samples.",
    "Despite data irregularities, {property} for {polymer} approximated {value} {unit}.",
    "Values recorded at {value} {unit} suggest a {property} pattern in {polymer}.",
    "Among tested materials, {polymer} displayed the highest {property} at {value}{unit}.",
    "Increased temperature raised the {property} of {polymer} to {value} {unit}.",
    "This transition, noted in {polymer}, likely corresponds to a {property} of {value} {unit}.",
    "Without clear labeling, the {value} {unit} value is tentatively assigned to {property}.",
    "{symbol} detected via TGA implies a {property} in {polymer} near {value} {unit}.",
    "{polymer} retains a strong {property} signal, centered at {value}{unit}.",
    "Curve inflection at {value} {unit} confirms the {property} for {polymer}.",
    "Compared to baseline, {polymer} showed an elevated {property} of {value} {unit}.",
    "{polymer} demonstrated dual performance with {symbol} ≈ {value}{unit} and {symbol} ≈ {value}{unit} under test conditions.",
    "After annealing, the material underwent structural reordering. Its {property} was later measured at {value} {unit}.",
    "The combination of {polymer} and additives shifted the {property} to {value} {unit}.",
    "After curing, {polymer} achieved a stable {property} around {value}{unit}.",
    "Unusual thermal behavior at {value} {unit} may reflect a unique {property} of {polymer}.",
    "Based on IR spectra, {property} in {polymer} was assumed to be {value} {unit}.",
    "Even without direct mention, {symbol} = {value} {unit} appears linked to {polymer}.",
    "{polymer} was tested under pressure, revealing {property} near {value} {unit}.",
    "The observed {value}{unit} spike correlates with {polymer}'s {property}.",
    "Symbol {symbol} marked a peak at {value}{unit} during testing of {polymer}.",
    "A sharp increase to {value} {unit} indicates an onset {property} in {polymer}.",
    "Both {property} and thermal resilience were noted in {polymer} at {value} {unit}.",
    "Thermal reflow caused {polymer}'s {property} to shift toward {value}{unit}.",
    "{symbol} aligned with theoretical predictions at {value}{unit} for {polymer}.",
    "An anomaly around {value} {unit} was possibly due to {property} behavior in {polymer}.",
    "Deviations in {property} occurred at {value}{unit}, particularly for {polymer} blends.",
    "Composite forms of {polymer} yielded {property} of {value} {unit} post-sintering.",
    "Variability in {property} was reduced after {polymer} annealed at {value}{unit}.",
    "Double peaks suggest two distinct {property} states in {polymer}: one at {value}{unit}.",
    "Although occluded by noise, a {value} {unit} reading supports known {property} for {polymer}.",
    "Covalent bonding in {polymer} influenced its {property}, placing it at {value} {unit}.",
    "The reported {value} {unit} aligns with previous estimates of {property} for {polymer}.",
    "Initial tests showed no significant behavior. However, {symbol} increased sharply to {value} {unit} in {polymer}.",
    "We examined the compound at varying temperatures. A {property} response emerged near {value}{unit} for {polymer}.",
    "As observed in DSC, {polymer} exhibits a {property} at {value} {unit}.",
    "Upon heating, {property} shifted to {value}{unit} for {polymer}.",
    "FTIR revealed {symbol} at ~{value}{unit} in the sample.",
    "{polymer}'s {property} fluctuated between {value}-{value} {unit}.",
    "An increase in {property} was recorded at {value}{unit} after curing.",
    "Post-annealing, {polymer} showed {symbol} ≈ {value}{unit}.",
    "The experiment yielded a peak {property} of {value} {unit}.",
    "{polymer} reached a maximum {symbol} of {value} {unit} under stress.",
    "Measurement indicated {property}={value}{unit} in {polymer}.",
    "Values of {value}{unit} correspond to {polymer}'s {property} region.",
    "The transition temperature (Tg) for {polymer} was determined as {value} {unit}.",
    "Recorded data show {symbol}: {value}{unit} in the cured network.",
    "At {value}{unit}, {property} behavior emerged in {polymer}.",
    "{symbol} was maintained near {value}{unit} for {polymer} over 2 h.",
    "Although noisy, a {value}{unit} peak was linked to {property}.",
    "Data suggest {polymer}'s {property} improved by {value}{unit}.",
    "A slight shift in {symbol} to {value}{unit} was detected in {polymer}.",
    "Analysis revealed {property} and {symbol} both present at {value}{unit}.",
    "{polymer} demonstrated {property} stability at {value} {unit}.",
    "Observed {symbol}: {value}{unit} consistent with theoretical predictions.",
    "An anomaly at {value}{unit} suggests a unique {property} in {polymer}.",
    "The reported {property} of {polymer} aligns with {value}{unit}.",
    "{symbol} measurements indicated fluctuations around {value} {unit}.",
    "{polymer} maintained {property} between {value}-{value} {unit} after aging.",
    "At {value}{unit}, a secondary transition was noted in {polymer}'s {property}.",
    "This value ({value}{unit}) is indicative of {property} onset in {polymer}.",
    "Tests showed {symbol} = {value}{unit} post thermal cycling.",
    "{polymer} achieved a {property} of {value}{unit} under compression.",
    "{symbol} peaked sharply to {value}{unit} during tensile testing of {polymer}.",
    "Experimental evidence places {polymer}'s {property} near {value}{unit}.",
    "IR absorption at {value}{unit} corresponds to {property} in {polymer}.",
    "The degradation temperature (Td) was recorded at {value}{unit}.",
    "{polymer}'s {symbol} remained stable at {value}{unit} during the test.",
    "Surprisingly, {property} increased to {value}{unit} after 10 cycles.",
    "The sample showed no detectable {property} below {value}{unit}.",
    "{symbol} and {property} exhibited coupled behavior in {polymer}.",
    "Annealing led to a {value}{unit} rise in {property} for {polymer}.",
    "The {property} dropped sharply to {value}{unit} after exposure.",
    "Data log: {polymer}, {symbol}={value}{unit}, {property} confirmed.",
    "Final assessment: {polymer} has a {property} of approximately {value}{unit}.",

    # New templates 101–300
    "The measured {property} of {polymer} was approximately {value}{unit}.",
    "Thermal analysis identified {symbol} at {value}{unit} for {polymer}.",
    "Upon heating, the {property} in {polymer} rose to {value}{unit}.",
    "DSC data show {polymer}'s {property} ranging from {value}–{value} {unit}.",
    "{polymer} retained its {property} near {value}{unit} after cycling.",
    "An observed {symbol} = {value}{unit} correlates with {polymer}'s thermal response.",
    "This study reports {property} in {polymer} with values of {value}{unit}.",
    "IR spectroscopy confirmed a {property} of {value}{unit} for {polymer}.",
    "At {value}{unit}, {symbol} indicated structural changes in {polymer}.",
    "During tensile testing, {polymer} exhibited a {property} of {value}{unit}.",
    "{polymer}'s {symbol} remained constant across multiple tests at {value}{unit}.",
    "A significant {property} shift was noted at {value}{unit} in {polymer}.",
    "The baseline {property} value of {polymer} was {value}{unit}.",
    "Differential scanning revealed {symbol} ≈ {value}{unit} for {polymer}.",
    "{polymer} was characterized by a {property} of {value}{unit} post-curing.",
    "A unique {property} signature at {value}{unit} was detected in {polymer}.",
    "Analysis of mechanical properties shows {polymer}'s {property} near {value}{unit}.",
    "After exposure to stress, {symbol} for {polymer} peaked at {value}{unit}.",
    "{symbol} fluctuations between {value}–{value} {unit} were observed in {polymer}.",
    "Recorded {property} values in {polymer} were centered at {value}{unit}.",
    "Thermal degradation led to a {property} decrease to {value}{unit} in {polymer}.",
    "A {property} of {value}{unit} was found to be consistent across {polymer} samples.",
    "The secondary {symbol} peak was observed near {value}{unit} for {polymer}.",
    "{polymer}'s {property} was stable under prolonged heating at {value}{unit}.",
    "Measurements indicate a {symbol} value of {value}{unit} in {polymer}.",
    "Curing resulted in a {property} shift from {value} to {value}{unit} for {polymer}.",
    "In tensile tests, {polymer} showed a {property} near {value}{unit}.",
    "Peak {symbol} was detected at {value}{unit} in {polymer} blends.",
    "The study measured {polymer}'s {property} at {value}{unit} using standard methods.",
    "An anomaly in {polymer} indicated {property} onset at {value}{unit}.",
    "Dynamic mechanical analysis revealed {symbol} ≈ {value}{unit} for {polymer}.",
    "At {value}{unit}, the {property} of {polymer} reached its maximum.",
    "This work found a {property} of {value}{unit} for biobased {polymer}.",
    "{symbol} = {value}{unit} suggests enhanced thermal stability in {polymer}.",
    "Heating cycles showed {polymer}'s {property} rising to {value}{unit}.",
    "Under load, {polymer} maintained {symbol} near {value}{unit}.",
    "The reported {property} in {polymer} was consistent with literature: {value}{unit}.",
    "Experimental evaluation of {polymer} yielded {symbol} values at {value}{unit}.",
    "{polymer} demonstrated a {property} of {value}{unit} in compression testing.",
    "Residual {symbol} readings centered at {value}{unit} for {polymer}.",
    "Peak {property} was observed at {value}{unit} during DMA of {polymer}.",
    "Thermogravimetric data place {property} at {value}{unit} in {polymer}.",
    "For the tested {polymer}, {symbol} averaged {value}{unit}.",
    "Results indicate {polymer} retains {property} at {value}{unit} under strain.",
    "A notable shift to {value}{unit} in {property} occurred during heating.",
    "Curve analysis suggests {polymer} {property} stabilized at {value}{unit}.",
    "The combination of additives shifted {property} in {polymer} to {value}{unit}.",
    "{symbol} readings at {value}{unit} were reproducible across {polymer} batches.",
    "Post-processing, {polymer} exhibited {property} of {value}{unit}.",
    "The characteristic {symbol} value of {polymer} was {value}{unit}.",
    "Thermal cycling produced a {property} plateau at {value}{unit} in {polymer}.",
    "{symbol} was maintained near {value}{unit} during extended testing of {polymer}.",
    "The experiment yielded a consistent {property} of {value}{unit} for {polymer}.",
    "Deviations in {symbol} were noted at {value}{unit} in {polymer} structures.",
    "A notable {property} change was observed near {value}{unit} in {polymer}.",
    "{polymer}'s {symbol} exhibited minimal variance around {value}{unit}.",
    "Dynamic testing revealed a {property} of {value}{unit} for {polymer}.",
    "Upon exposure to solvents, {polymer} maintained {property} at {value}{unit}.",
    "Peak thermal stability was indicated by {symbol} ≈ {value}{unit} for {polymer}.",
    "{property} trends in {polymer} were centered on {value}{unit}.",
    "The characteristic temperature ({symbol}) was measured at {value}{unit} for {polymer}.",
    "No significant shifts in {property} were noted below {value}{unit} for {polymer}.",
    "Tests determined a {symbol} of {value}{unit} for {polymer} blends.",
    "Average {property} of {polymer} was reported at {value}{unit}.",
    "An unexpected rise in {symbol} to {value}{unit} was recorded for {polymer}.",
    "{polymer} retained a {property} of {value}{unit} after aging protocols.",
    "Peak heat capacity readings placed {symbol} at {value}{unit} for {polymer}.",
    "This analysis confirmed a {property} of {value}{unit} for {polymer}.",
    "Tensile tests showed {symbol} values clustering near {value}{unit} for {polymer}.",
    "{property} was stable at {value}{unit} in all {polymer} configurations tested.",
    "The degradation onset was observed at {value}{unit} for {polymer}'s {property}.",
    "Reprocessing cycles left {polymer}'s {symbol} unchanged at {value}{unit}.",
    "A notable increase to {value}{unit} in {property} was found after thermal treatment.",
    "Stress-strain analysis placed {symbol} at {value}{unit} for {polymer}.",
    "{property} values remained consistent at {value}{unit} despite repeated tests.",
    "In FTIR, absorption bands suggested {property} near {value}{unit} for {polymer}.",
    "Experiments showed {symbol} rising sharply to {value}{unit} during testing of {polymer}.",
    "{polymer}'s thermal conductivity ({property}) was measured as {value}{unit}.",
    "A consistent {symbol} value of {value}{unit} was recorded in {polymer} blends.",
    "Thermal transitions placed {property} onset at {value}{unit} for {polymer}.",
    "The combination of {polymer} and fillers yielded {property} of {value}{unit}.",
    "Post-synthesis, {symbol} stabilized near {value}{unit} for {polymer}.",
    "Studies identified a {property} of {value}{unit} in {polymer} composites.",
    "Curing temperature affected {symbol} values, peaking at {value}{unit} in {polymer}.",
    "Consistent {property} readings around {value}{unit} were observed for {polymer}.",
    "{polymer}'s {symbol} was maintained at {value}{unit} under stress.",
    "High temperature caused {property} decline to {value}{unit} in {polymer}.",
    "Testing confirmed a steady {symbol} of {value}{unit} for {polymer}.",
    "Anomalous behavior in {polymer} was marked by {property} at {value}{unit}.",
    "Data suggests {polymer} retains its {property} up to {value}{unit}.",
    "At {value}{unit}, {symbol} reached a plateau in {polymer}.",
    "{polymer}'s thermal resistance ({property}) was found at {value}{unit}.",
    "Observed {symbol} data showed peaks around {value}{unit} for {polymer}.",
    "Post-aging, {polymer} showed {property} = {value}{unit}.",
    "Experiments placed {property} onset at {value}{unit} for {polymer}.",
    "{symbol} peaks were stable at {value}{unit} after thermal cycling of {polymer}.",
    "{property} stability was confirmed at {value}{unit} for {polymer} across batches.",
    "After reprocessing, {symbol} remained at {value}{unit} for {polymer} materials.",
    "A sharp drop in {property} to {value}{unit} occurred during thermal degradation.",
    "{symbol} was maintained near {value}{unit} across all {polymer} samples.",
    "The noted {property} was measured consistently at {value}{unit} for {polymer}.",
    "{symbol} detected in DMA was approximately {value}{unit} for {polymer}.",
    "{polymer}'s mechanical resilience ({property}) was confirmed at {value}{unit}.",
    "A {value}{unit} value was observed, linked to {polymer}'s {symbol} behavior.",
    "Thermal reflow did not alter {property}, which stayed at {value}{unit} for {polymer}.",
    "{symbol} for {polymer} averaged {value}{unit} in all experimental runs.",
    "{polymer} was characterized by {property} values of {value}{unit}.",
    "Stress relaxation indicated {symbol} ≈ {value}{unit} in {polymer}.",
    "Post-curing, {polymer} showed {property} stability at {value}{unit}.",
    "Measurements indicate an average {symbol} of {value}{unit} for {polymer}.",
    "{property} decreased slightly to {value}{unit} in aged {polymer} samples.",
    "{symbol} readings remained at {value}{unit} even after thermal cycling of {polymer}.",
    "The material retained {property} at {value}{unit} post mechanical stress.",
    "{symbol} was recorded near {value}{unit} under load testing for {polymer}.",
    "Experimental results highlight a {property} of {value}{unit} in {polymer}.",
    "{polymer} exhibited {symbol} fluctuations around {value}{unit}.",
    "The {property} of {polymer} was consistently measured at {value}{unit}.",
    "Stress testing revealed {symbol} = {value}{unit} for {polymer}.",
    "{polymer} displayed no {property} change below {value}{unit}.",
    "Observed {symbol} data placed peaks around {value}{unit} for {polymer}.",
    "This work measured {property} at {value}{unit} in {polymer} composites.",

    # Templates 1–50
    "The {property} ({symbol}) of {polymer} was found to be {value} {unit}.",
    "In {polymer}, the {property} ({symbol}) reached {value}{unit}.",
    "{property} values ({symbol}) recorded for {polymer}: {value}{unit}.",
    "We observed a shift in {property} ({symbol}) at {value}{unit} for {polymer}.",
    "{polymer}'s {property} ({symbol}) was approximately {value}{unit}.",
    "Tests yielded {symbol} ({property}) ≈ {value}{unit} for {polymer}.",
    "The analysis determined ({symbol}) {value}{unit} corresponding to {polymer}.",
    "A notable {property} ({symbol}) peak appeared near {value}{unit}.",
    "Measurements indicate {property} ({symbol}) values of {value}{unit}.",
    "{symbol} ({value}{unit}) was associated with {polymer}'s {property}.",
    "At {value}{unit}, a secondary {property} ({symbol}) was noted in {polymer}.",
    "{polymer} exhibited consistent {property} ({symbol}={value}{unit}).",
    "Experiments showed {property} ({symbol}={value}{unit}) for {polymer}.",
    "The recorded value ({value}{unit}) matched {property} ({symbol}) in {polymer}.",
    "{symbol} ({value}{unit}) was indicative of {polymer}'s {property}.",
    "A {property} ({symbol}) of {value}{unit} was identified after annealing.",
    "For {polymer}, {property} ({symbol}) stabilized near {value}{unit}.",
    "{symbol} values ({value}{unit}) confirmed thermal changes in {polymer}.",
    "During curing, {polymer} exhibited {property} ({symbol}={value}{unit}).",
    "Data suggest a {property} ({symbol}) of {value}{unit} in {polymer}.",
    "Observed results: {property} ({symbol}) = {value}{unit} for {polymer}.",
    "The transition point ({symbol}) was measured at {value}{unit} in {polymer}.",
    "{polymer}'s behavior reflected a {property} ({symbol}) of {value}{unit}.",
    "The peak {symbol} ({property}) was recorded at {value}{unit}.",
    "A strong correlation was found for {property} ({symbol}) at {value}{unit}.",
    "Post-treatment, {polymer} retained {property} ({symbol}) at {value}{unit}.",
    "Characteristic {symbol} ({value}{unit}) implies a {property} in {polymer}.",
    "Thermal response was linked to {property} ({symbol}) = {value}{unit}.",
    "This research measured {property} ({symbol}) at {value}{unit} for {polymer}.",
    "Anomalous behavior: {property} ({symbol}) peaked at {value}{unit}.",
    "Curing process led to {symbol} ({property}) readings of {value}{unit}.",
    "At {value}{unit}, {property} ({symbol}) transitions occurred in {polymer}.",
    "A new peak at ({symbol}={value}{unit}) suggested altered {property}.",
    "{symbol} ({value}{unit}) trends indicated changes in {property}.",
    "{property} ({symbol}) was measured for {polymer}: {value}{unit}.",
    "Dynamic tests showed {property} ({symbol}) ≈ {value}{unit}.",
    "FTIR identified {property} ({symbol}={value}{unit}) in {polymer}.",
    "For {polymer}, {property} was recorded as ({symbol}={value}{unit}).",
    "This dataset confirms {property} ({symbol}) = {value}{unit} for {polymer}.",
    "A gradual shift in {symbol} ({value}{unit}) marked {property} change.",
    "{polymer} showed no {property} below ({symbol}={value}{unit}).",
    "{symbol} peaks ({value}{unit}) align with {property} in {polymer}.",
    "Experimental analysis found {property} ({symbol}) near {value}{unit}.",
    "The secondary peak ({symbol}) occurred at {value}{unit} for {polymer}.",
    "We observed {property} values ({symbol}) between {value}–{value}{unit}.",
    "Annealing caused {property} ({symbol}) to rise to {value}{unit}.",
    "Thermal analysis confirmed {symbol} ({property}) ≈ {value}{unit}.",
    "Notably, {property} ({symbol}) shifted towards {value}{unit} in {polymer}.",
    "Observed data: {property} ({symbol}) at {value}{unit} for {polymer}.",
    "{symbol} ({value}{unit}) was found consistent with {polymer}'s {property}.",

    # Templates 51–100
    "{polymer}'s {symbol} ({value}{unit}) suggests a stable {property}.",
    "TGA reported {property} ({symbol}) = {value}{unit} for {polymer}.",
    "A clear {symbol} ({value}{unit}) was linked to {property} in {polymer}.",
    "This study measured {property} ({symbol}) of {value}{unit}.",
    "{symbol} ({value}{unit}) confirmed {property} consistency in {polymer}.",
    "At ({symbol}={value}{unit}), significant changes in {property} emerged.",
    "{property} was identified via {symbol} readings ({value}{unit}).",
    "The experimental curve showed {symbol} ({value}{unit}) for {property}.",
    "Anomalies in {symbol} ({value}{unit}) highlight shifts in {property}.",
    "Peak values: {property} ({symbol}) at {value}{unit} in {polymer}.",
    "Repeated tests confirmed {property} ({symbol}) ≈ {value}{unit}.",
    "{polymer} retained a consistent {symbol} ({value}{unit}) across trials.",
    "The average {property} ({symbol}) for {polymer} was {value}{unit}.",
    "This aligns with known {property} ({symbol}) = {value}{unit}.",
    "Observed fluctuation in {symbol} ({value}{unit}) relates to {property}.",
    "The data showed {property} ({symbol}) stability at {value}{unit}.",
    "{symbol} measurements ({value}{unit}) support prior {property} findings.",
    "Thermal plots revealed {property} ({symbol}) at {value}{unit}.",
    "{property} values were found as ({symbol}={value}{unit}) in {polymer}.",
    "{symbol} indicated a peak at ({value}{unit}) for {property}.",
    "No clear {property} detected below {symbol} ({value}{unit}).",
    "A clear transition in {property} ({symbol}) appeared at {value}{unit}.",
    "During DMA, {property} ({symbol}) = {value}{unit} was measured.",
    "{symbol} readings ({value}{unit}) marked onset of {property} in {polymer}.",
    "{polymer} presented stable {property} ({symbol}) after {value}{unit}.",
    "{symbol} ({value}{unit}) confirms a robust {property} in {polymer}.",
    "{property} showed fluctuations, with {symbol} ranging {value}-{value}{unit}.",
    "We recorded {property} ({symbol}) values of {value}{unit}.",
    "Experimental error was minimal for {symbol} ({value}{unit}) readings.",
    "{property} ({symbol}) = {value}{unit} agrees with theoretical models.",
    "This report details {symbol} ({value}{unit}) and {property} behavior.",
    "Peak {symbol} ({value}{unit}) reflected enhanced {property}.",
    "{polymer} exhibited {property} stability at ({symbol}={value}{unit}).",
    "During reflow, {property} ({symbol}) shifted to {value}{unit}.",
    "{symbol} values ({value}{unit}) remained unchanged post-aging.",
    "An outlier: {property} ({symbol}) at {value}{unit} for {polymer}.",
    "{property} readings ({symbol}) averaged around {value}{unit}.",
    "{symbol} values ({value}{unit}) confirmed a secondary {property}.",
    "We noted a {property} ({symbol}) decrease to {value}{unit}.",
    "Dynamic testing gave {symbol} ({value}{unit}) for {polymer}.",
    "{property} ({symbol}) remained constant across all {polymer} samples.",
    "Unexpected results: {symbol} ({value}{unit}) linked to {property}.",
    "For {polymer}, thermal shifts yielded {property} ({symbol}) ≈ {value}{unit}.",
    "Recorded {symbol} ({value}{unit}) suggestive of {property} change.",
    "The characteristic point ({symbol}={value}{unit}) marked {property} onset.",
    "Average values: {property} ({symbol}) of {value}{unit} in {polymer}.",
    "Experiments show {property} ({symbol}) ≈ {value}{unit} under stress.",
    "IR data highlighted {symbol} ({value}{unit}) peaks in {property}.",
    "{property} readings ({symbol}) clustered around {value}{unit}.",
    "The thermal profile featured {symbol} ({value}{unit}) for {property}.",

    # Templates 1–50
    "After annealing at {value}{unit}, {polymer} exhibited a {property} increase.",
    "{polymer} was cured for 3 hours, leading to a {property} of {value}{unit}.",
    "Although {polymer} showed initial stability, its {property} dropped to {value}{unit}.",
    "The {property} improved significantly after thermal cycling at {value}{unit}.",
    "{polymer} was heated to {value}{unit} before testing, revealing {property} changes.",
    "As a result of the aging process, {polymer}'s {property} reached {value}{unit}.",
    "The thermal treatment at {value}{unit} caused {property} shifts in {polymer}.",
    "Following solvent evaporation, {polymer} displayed a {property} near {value}{unit}.",
    "{property} decreased when {polymer} was exposed to humidity for 72 hours.",
    "While initial tests showed {property} at {value}{unit}, annealing reduced it.",
    "{symbol} values fluctuated during reflow, eventually stabilizing at {value}{unit}.",
    "{polymer}'s {property} was enhanced due to crosslinking at {value}{unit}.",
    "The heating rate of 10°C/min affected {polymer}'s {property}, raising it to {value}{unit}.",
    "After stress relaxation tests, {polymer} retained {property} of {value}{unit}.",
    "{property} reached {value}{unit} post-curing, despite initial fluctuations.",
    "Mechanical stress applied to {polymer} led to a {property} increase of {value}{unit}.",
    "As temperature rose, {polymer}'s {property} decreased gradually to {value}{unit}.",
    "Following exposure to UV light, {polymer} developed a {property} at {value}{unit}.",
    "{polymer} exhibited {property} stability up to {value}{unit} after treatment.",
    "Although measurements varied, {property} averaged {value}{unit} in {polymer}.",
    "Curing conditions altered {property}, which stabilized at {value}{unit} for {polymer}.",
    "Repeated thermal cycling caused a shift in {property} to {value}{unit}.",
    "Post-synthesis, {polymer}'s {property} was determined as {value}{unit}.",
    "As solvent evaporated, {symbol} increased steadily to {value}{unit}.",
    "{polymer} displayed reduced {property} after prolonged heating at {value}{unit}.",
    "Annealing and crosslinking yielded {property} of {value}{unit} in {polymer}.",
    "Following tensile testing, {polymer} showed {property} values near {value}{unit}.",
    "While most samples maintained {property}, {polymer} dropped to {value}{unit}.",
    "{property} for {polymer} was found to decrease over time to {value}{unit}.",
    "{polymer} achieved {property} stability after heating at {value}{unit} for 5 h.",
    "Gradual heating resulted in a {property} plateau at {value}{unit} for {polymer}.",
    "{symbol} rose sharply during the test before leveling off at {value}{unit}.",
    "Aging under pressure shifted {polymer}'s {property} to {value}{unit}.",
    "After exposure to moisture, {property} fell to {value}{unit} in {polymer}.",
    "{property} climbed to {value}{unit} after 10 cycles of thermal reflow.",
    "Upon cooling from {value}{unit}, {polymer}'s {property} increased slightly.",
    "Post-processing changes brought {property} to {value}{unit} in {polymer}.",
    "Although annealed at {value}{unit}, {polymer} showed minimal {property} variation.",
    "During high-temperature tests, {symbol} peaked at {value}{unit}.",
    "{polymer} maintained {property} consistency despite thermal cycling at {value}{unit}.",
    "With increasing strain, {property} reached a maximum at {value}{unit}.",
    "{property} changes lagged behind {symbol} variations, stabilizing at {value}{unit}.",
    "As mechanical load increased, {property} approached {value}{unit}.",
    "{symbol} measurements indicated {property} onset around {value}{unit}.",
    "Repeated stress resulted in {property} values hovering near {value}{unit}.",
    "Though initially stable, {polymer} lost {property} after heating at {value}{unit}.",
    "Exposure to light raised {symbol}, leading to {property} of {value}{unit}.",
    "Post-curing, {polymer}'s {property} varied slightly but settled at {value}{unit}.",
    "In the second test cycle, {symbol} climbed to {value}{unit}, affecting {property}.",
    "{property} declined steadily following storage at {value}{unit} for 7 days.",

    # Templates 1–50
    "After annealing at {value}{unit}, {polymer} exhibited a {property} increase.",
    "{polymer} was cured for 3 hours, leading to a {property} of {value}{unit}.",
    "Although {polymer} showed initial stability, its {property} dropped to {value}{unit}.",
    "The {property} improved significantly after thermal cycling at {value}{unit}.",
    "{polymer} was heated to {value}{unit} before testing, revealing {property} changes.",
    "As a result of the aging process, {polymer}'s {property} reached {value}{unit}.",
    "The thermal treatment at {value}{unit} caused {property} shifts in {polymer}.",
    "Following solvent evaporation, {polymer} displayed a {property} near {value}{unit}.",
    "{property} decreased when {polymer} was exposed to humidity for 72 hours.",
    "While initial tests showed {property} at {value}{unit}, annealing reduced it.",
    "{symbol} values fluctuated during reflow, eventually stabilizing at {value}{unit}.",
    "{polymer}'s {property} was enhanced due to crosslinking at {value}{unit}.",
    "The heating rate of 10°C/min affected {polymer}'s {property}, raising it to {value}{unit}.",
    "After stress relaxation tests, {polymer} retained {property} of {value}{unit}.",
    "{property} reached {value}{unit} post-curing, despite initial fluctuations.",
    "Mechanical stress applied to {polymer} led to a {property} increase of {value}{unit}.",
    "As temperature rose, {polymer}'s {property} decreased gradually to {value}{unit}.",
    "Following exposure to UV light, {polymer} developed a {property} at {value}{unit}.",
    "{polymer} exhibited {property} stability up to {value}{unit} after treatment.",
    "Although measurements varied, {property} averaged {value}{unit} in {polymer}.",
    "Curing conditions altered {property}, which stabilized at {value}{unit} for {polymer}.",
    "Repeated thermal cycling caused a shift in {property} to {value}{unit}.",
    "Post-synthesis, {polymer}'s {property} was determined as {value}{unit}.",
    "As solvent evaporated, {symbol} increased steadily to {value}{unit}.",
    "{polymer} displayed reduced {property} after prolonged heating at {value}{unit}.",
    "Annealing and crosslinking yielded {property} of {value}{unit} in {polymer}.",
    "Following tensile testing, {polymer} showed {property} values near {value}{unit}.",
    "While most samples maintained {property}, {polymer} dropped to {value}{unit}.",
    "{property} for {polymer} was found to decrease over time to {value}{unit}.",
    "{polymer} achieved {property} stability after heating at {value}{unit} for 5 h.",
    "Gradual heating resulted in a {property} plateau at {value}{unit} for {polymer}.",
    "{symbol} rose sharply during the test before leveling off at {value}{unit}.",
    "Aging under pressure shifted {polymer}'s {property} to {value}{unit}.",
    "After exposure to moisture, {property} fell to {value}{unit} in {polymer}.",
    "{property} climbed to {value}{unit} after 10 cycles of thermal reflow.",
    "Upon cooling from {value}{unit}, {polymer}'s {property} increased slightly.",
    "Post-processing changes brought {property} to {value}{unit} in {polymer}.",
    "Although annealed at {value}{unit}, {polymer} showed minimal {property} variation.",
    "During high-temperature tests, {symbol} peaked at {value}{unit}.",
    "{polymer} maintained {property} consistency despite thermal cycling at {value}{unit}.",
    "With increasing strain, {property} reached a maximum at {value}{unit}.",
    "{property} changes lagged behind {symbol} variations, stabilizing at {value}{unit}.",
    "As mechanical load increased, {property} approached {value}{unit}.",
    "{symbol} measurements indicated {property} onset around {value}{unit}.",
    "Repeated stress resulted in {property} values hovering near {value}{unit}.",
    "Though initially stable, {polymer} lost {property} after heating at {value}{unit}.",
    "Exposure to light raised {symbol}, leading to {property} of {value}{unit}.",
    "Post-curing, {polymer}'s {property} varied slightly but settled at {value}{unit}.",
    "In the second test cycle, {symbol} climbed to {value}{unit}, affecting {property}.",
    "{property} declined steadily following storage at {value}{unit} for 7 days.",

    # Templates 51–100
    "When cooled rapidly, {polymer} retained {property} at {value}{unit}.",
    "Under sustained load, {property} of {polymer} stabilized at {value}{unit}.",
    "{property} shifted from {value}{unit} to {value}{unit} during testing.",
    "Heating above {value}{unit} resulted in permanent changes to {property}.",
    "{symbol} varied with strain rate, reaching {value}{unit} at peak load.",
    "{polymer} showed a drop in {property} after cycling between {value}{unit} and {value}{unit}.",
    "Although exposed to solvent, {polymer}'s {property} remained near {value}{unit}.",
    "Thermal degradation initiated at {value}{unit}, affecting {property}.",
    "{property} gradually increased as {polymer} was exposed to heat treatment.",
    "Despite moisture ingress, {polymer} maintained {property} of {value}{unit}.",
    "Post-curing conditions led to {property} increase at {value}{unit}.",
    "As {polymer} aged, {property} fell to a minimum of {value}{unit}.",
    "{symbol} fluctuated across cycles before stabilizing at {value}{unit}.",
    "The heating rate altered {property}, which peaked at {value}{unit}.",
    "Extended annealing raised {polymer}'s {property} to {value}{unit}.",
    "The experimental setup caused {symbol} variations near {value}{unit}.",
    "While cooling, {property} declined from {value}{unit} to {value}{unit}.",
    "UV exposure shifted {property} in {polymer} up to {value}{unit}.",
    "Increased crosslink density resulted in {property} of {value}{unit}.",
    "{symbol} was delayed by thermal lag, finally peaking at {value}{unit}.",
    "Shear stress led to {property} drop in {polymer} at {value}{unit}.",
    "{polymer} was aged at {value}{unit}, yielding stable {property}.",
    "Repeated heating cycles altered {symbol}, observed at {value}{unit}.",
    "Stress-strain analysis revealed {property} changes near {value}{unit}.",
    "Although processed differently, {polymer} retained {property} of {value}{unit}.",
    "Cooling to {value}{unit} resulted in enhanced {property} for {polymer}.",
    "Exposure to oxidizing conditions lowered {property} to {value}{unit}.",
    "{symbol} remained unchanged during cycling at {value}{unit}.",
    "{polymer}'s {property} increased linearly with temperature to {value}{unit}.",
    "Annealing effects became evident as {property} rose to {value}{unit}.",
    "Moisture exposure had no effect on {property} of {polymer}.",
    "A transient {symbol} response was detected near {value}{unit}.",
    "Mechanical fatigue caused a decline in {property} to {value}{unit}.",
    "Thermal shock resulted in sudden {property} changes at {value}{unit}.",
    "The peak {symbol} aligned with theoretical expectations at {value}{unit}.",
    "Extended UV irradiation altered {property}, observed at {value}{unit}.",
    "During synthesis, {property} stabilized at {value}{unit}.",
    "Subsequent cooling to {value}{unit} restored {property} in {polymer}.",
    "Repeated tension reduced {property} to {value}{unit} for {polymer}.",
    "{polymer}'s {property} remained constant despite cyclic stress.",
    "After pressure cycling, {symbol} settled near {value}{unit}.",
    "Post-treatment, {property} values ranged from {value}{unit} to {value}{unit}.",
    "A small rise in {property} was observed during prolonged testing.",
    "Humidity exposure drove {property} downward to {value}{unit}.",
    "Thermal processing altered {symbol}, peaking at {value}{unit}.",
    "In tensile testing, {polymer}'s {property} peaked at {value}{unit}.",
    "Fatigue tests revealed a steady {property} decline at {value}{unit}.",
    "After 24 hours at {value}{unit}, {polymer}'s {property} stabilized.",
    "Mechanical creep reduced {property} to {value}{unit} over time.",

    # Templates 1–50
    "Table 1: {polymer} – {property}: {value}{unit}",
    "Table 2 lists the {property} of {polymer} measured as {value}{unit}.",
    "Fig. 3 shows {symbol} for {polymer}, recorded at {value}{unit}.",
    "Figure 4: {polymer} sample exhibiting {property} of {value}{unit}.",
    "{property} ({symbol}) for {polymer}: {value}{unit} [Table 5]",
    "Caption: Thermal analysis results for {polymer} ({value}{unit} for {property})",
    "Table S2: {polymer} ({symbol}): {value}{unit}",
    "Figure S1 highlights {polymer} with {property} near {value}{unit}.",
    "Data Table: {property} ({symbol}) = {value}{unit}, Material: {polymer}",
    "Table 3 (continued): {polymer}, {property}: {value}{unit}",
    "Entry: {polymer} | {property}={value}{unit} | Ref. [12]",
    "Dataset: {symbol}={value}{unit}, Polymer={polymer}, Test={property}",
    "Fig. 5 illustrates {polymer}'s {property} at {value}{unit}.",
    "Supplementary Table 6: {polymer}, {property}: {value}{unit}",
    "Results: {polymer} achieved {property} = {value}{unit} [see Table 1].",
    "{symbol} measured for {polymer}: {value}{unit} (Table 4)",
    "Fig. 2b – {polymer}, {property}: {value}{unit}",
    "Figure legend: {polymer} ({symbol}) at {value}{unit}.",
    "Table S3 summary: {polymer} {property}: {value}{unit}",
    "{polymer} data (Table 7): {property} – {value}{unit}",
    "Fig. S4 – {polymer} exhibits {property} near {value}{unit}.",
    "Data summary: {property}={value}{unit}, Polymer: {polymer}",
    "Table entry: {polymer}, {symbol}: {value}{unit}",
    "Results Table: {polymer} | {property}: {value}{unit}",
    "Supplementary Fig. S5 highlights {symbol}={value}{unit} for {polymer}.",
    "Dataset line: {polymer}, {property}={value}{unit}",
    "Table 8 includes {polymer} with {property}: {value}{unit}",
    "Figure 9 – {polymer}'s {property} at {value}{unit}",
    "Result row: {symbol}={value}{unit}, Polymer={polymer}",
    "Captions: {polymer} | {symbol}: {value}{unit}",
    "Table S6 overview: {polymer}, {property}={value}{unit}",
    "Fig. 10: {polymer} ({property}) at {value}{unit}",
    "Recorded: {property}={value}{unit}, {polymer} sample",
    "Summary table: {polymer}, {symbol}: {value}{unit}",
    "Table note: {polymer}'s {property} found at {value}{unit}",
    "Dataset S4 shows {polymer} {property}={value}{unit}",
    "Fig. S2 caption: {polymer}, {symbol}={value}{unit}",
    "Supplementary results: {property}={value}{unit}, {polymer}",
    "Table 11: {polymer} {property} = {value}{unit}",
    "Data entry: {symbol}={value}{unit}, Polymer={polymer}",
    "Results summary (Table S7): {polymer}, {property}={value}{unit}",
    "Fig. 11 highlights {polymer}, {symbol}: {value}{unit}",
    "Overview: {polymer} {property}={value}{unit} (Table 12)",
    "Supporting Table 13: {polymer}, {property}: {value}{unit}",
    "Tabulated: {polymer}, {symbol}={value}{unit}",
    "Figure caption: {polymer} – {property}: {value}{unit}",
    "Table result: {polymer} with {property}={value}{unit}",
    "Dataset excerpt: {polymer} | {symbol}: {value}{unit}",
    "Results: {symbol}={value}{unit} for {polymer} (Fig. S6).",

    # Templates 51–100
    "Table S8 lists {polymer} {property}: {value}{unit}",
    "Data row: {polymer}, {property}={value}{unit}",
    "Fig. S7 caption: {polymer} ({symbol}={value}{unit})",
    "Summary Table: {polymer}, {property}={value}{unit}",
    "Dataset entry: {polymer} | {property}: {value}{unit}",
    "Fig. S8 – {polymer} shows {symbol}={value}{unit}",
    "Results Table 15: {polymer}, {property}={value}{unit}",
    "Supporting data: {symbol}={value}{unit}, Polymer={polymer}",
    "Table 16 – {polymer}'s {property}: {value}{unit}",
    "Tabulated data: {polymer}, {property}={value}{unit}",
    "Dataset line: {polymer} ({symbol}): {value}{unit}",
    "Figure S9: {polymer}, {property}={value}{unit}",
    "Table S10 entry: {polymer} {property}: {value}{unit}",
    "Summary caption: {polymer}, {symbol}: {value}{unit}",
    "Results dataset: {polymer}, {property}={value}{unit}",
    "Table 17 highlights {polymer}'s {property}={value}{unit}",
    "Results summary: {polymer}, {property}={value}{unit}",
    "Figure label: {polymer}, {symbol}: {value}{unit}",
    "Dataset S11 includes {polymer}, {property}={value}{unit}",
    "Tabulated results: {polymer}, {symbol}={value}{unit}",
    "Supporting figure: {polymer}, {property}: {value}{unit}",
    "Table note: {polymer}, {property}={value}{unit}",
    "Result row: {polymer} – {symbol}: {value}{unit}",
    "Summary Table: {polymer}, {property}={value}{unit}",
    "Caption text: {polymer} {property}={value}{unit}",
    "Results list: {symbol}={value}{unit} ({polymer})",
    "Tabulated entry: {polymer} | {property}: {value}{unit}",
    "Dataset Table: {polymer}, {symbol}: {value}{unit}",
    "Fig. S12 caption: {polymer}, {property}={value}{unit}",
    "Summary results: {polymer}, {property}={value}{unit}",
    "Data Table 18: {polymer}, {symbol}: {value}{unit}",
    "Supporting results: {property}={value}{unit}, {polymer}",
    "Entry line: {polymer}, {property}={value}{unit}",
    "Fig. 13 caption: {polymer} ({symbol}={value}{unit})",
    "Summary Table: {polymer}, {property}={value}{unit}",
    "Results dataset: {polymer} | {property}: {value}{unit}",
    "Table 19 – {polymer}, {property}={value}{unit}",
    "Caption overview: {polymer}, {symbol}: {value}{unit}",
    "Dataset excerpt: {polymer}, {property}={value}{unit}",
    "Results log: {symbol}={value}{unit} ({polymer})",
    "Table note: {polymer}, {property}={value}{unit}",
    "Fig. S14 – {polymer}, {symbol}: {value}{unit}",
    "Data entry: {polymer}, {property}={value}{unit}",
    "Summary Table: {polymer}, {property}={value}{unit}",
    "Caption text: {symbol}={value}{unit} for {polymer}.",
    "Supporting Table 20: {polymer}, {property}={value}{unit}",
    "Dataset entry: {polymer}, {symbol}={value}{unit}.",
    "Results summary: {polymer}, {property}={value}{unit}.",
    "Figure caption: {polymer} with {symbol}={value}{unit}.",
    "Table note: {polymer}, {property}={value}{unit}.",
    "Tabulated result: {polymer}, {symbol}={value}{unit}.",

    # Templates 1–50
    "T g  = {value} • C for {polymer}",
    "Δ H ≈ {value} kJ mol^-1 in {polymer}",
    "{polymer} {property} approx {value}{unit}",
    "Value found: {property} {value} {unit} ({polymer})",
    "T g  : {value}{unit} - polymer: {polymer}",
    "Result {property}: {value} {unit} Material {polymer}",
    "OCR: {symbol} ~ {value}{unit} polymer={polymer}",
    "{property} is ~{value}{unit} in {polymer}",
    "{value} {unit} corresponds to {property} {polymer}",
    "T  g={value}degC polymer:{polymer}",
    "Measured {symbol} : {value}{unit} - sample: {polymer}",
    "{value}{unit} {property} ({polymer})",
    "{polymer} {symbol} found ~{value}{unit}",
    "Data {property}: {value}{unit} polymer: {polymer}",
    "{symbol}={value}{unit} ({polymer})",
    "OCR Artifact: {property} = {value}{unit} in {polymer}",
    "Recorded {symbol}:{value}{unit} polymer={polymer}",
    "T g  {value} deg C / {polymer}",
    "Found value: {value} {unit} for {property} in {polymer}",
    "Result: {symbol}~{value}{unit} material={polymer}",
    "{property}: {value}{unit} polymer={polymer}",
    "Observed {symbol}≈{value}{unit} ({polymer})",
    "OCR: {value} {unit} {property} {polymer}",
    "Measured {property} {value}{unit} – material {polymer}",
    "{symbol} {value}{unit} (detected in {polymer})",
    "T d : {value}{unit}, polymer={polymer}",
    "Artifact {property}: {value}{unit} [{polymer}]",
    "{property} : {value}{unit} polymer {polymer}",
    "Found: {symbol}={value}{unit}, material:{polymer}",
    "{property} ~{value}{unit} material={polymer}",
    "Reading {symbol}:{value}{unit} polymer:{polymer}",
    "Approx. {value}{unit} for {property} in {polymer}",
    "Result: {value}{unit} {property} [{polymer}]",
    "OCR Detected {symbol}={value}{unit} material={polymer}",
    "{property}={value}{unit} polymer={polymer}",
    "{symbol}≈{value}{unit} material={polymer}",
    "T g ~{value}{unit}, polymer={polymer}",
    "{property}: {value}{unit} found in {polymer}",
    "Detected {symbol}:{value}{unit} polymer={polymer}",
    "Artifact: {value}{unit} for {property} ({polymer})",
    "{symbol}: {value}{unit} OCR scan – {polymer}",
    "{value}{unit} ~ {property} polymer={polymer}",
    "OCR Reading: {symbol}={value}{unit} [{polymer}]",
    "{property}≈{value}{unit} material={polymer}",
    "{symbol} found: {value}{unit} polymer:{polymer}",
    "Result {property}: {value}{unit} sample:{polymer}",
    "Approx {value}{unit} corresponds to {property} ({polymer})",
    "Reading: {symbol} ~{value}{unit}, polymer:{polymer}",
    "Data artifact: {property}={value}{unit} ({polymer})",

    # Templates 51–100
    "OCR error: {value}{unit} {property} {polymer}",
    "{symbol} ≈ {value}{unit} found in {polymer}",
    "{property}~{value}{unit} polymer:{polymer}",
    "Result: {symbol}={value}{unit} ({polymer})",
    "OCR Detected: {property} {value}{unit} sample:{polymer}",
    "T g ={value}{unit} for material={polymer}",
    "Approximate {property}: {value}{unit} [{polymer}]",
    "Found {symbol}={value}{unit} polymer:{polymer}",
    "Value: {property}={value}{unit} Material:{polymer}",
    "Reading artifact {symbol}:{value}{unit} polymer={polymer}",
    "Data: {value}{unit} {property} ({polymer})",
    "{property}:{value}{unit} sample={polymer}",
    "OCR capture: {symbol}~{value}{unit} polymer={polymer}",
    "Approx {symbol}:{value}{unit} for {polymer}",
    "T d ~{value}{unit}, polymer:{polymer}",
    "{property}={value}{unit} OCR error – material={polymer}",
    "{symbol}={value}{unit} ({polymer}) detected",
    "Artifact: {value}{unit} for {property} polymer={polymer}",
    "Detected {property}~{value}{unit} sample:{polymer}",
    "{symbol} ≈ {value}{unit}, material:{polymer}",
    "T g ={value}{unit} found polymer={polymer}",
    "{property} value={value}{unit} material={polymer}",
    "Detected {symbol}={value}{unit} ({polymer})",
    "OCR Issue: {value}{unit} {property} polymer:{polymer}",
    "Result {property}:{value}{unit} Material={polymer}",
    "Approximation: {symbol}={value}{unit} polymer={polymer}",
    "OCR Captured {value}{unit} {property} [{polymer}]",
    "{property}: ~{value}{unit}, polymer:{polymer}",
    "Found {symbol}={value}{unit} (polymer={polymer})",
    "Measurement {property}={value}{unit} material:{polymer}",
    "OCR: {value}{unit} corresponds to {property} {polymer}",
    "Detected {symbol}={value}{unit} in polymer:{polymer}",
    "Result {property}: {value}{unit} sample:{polymer}",
    "Approx {symbol}:{value}{unit}, polymer={polymer}",
    "Data artifact: {property}={value}{unit} [{polymer}]",
    "OCR Error {value}{unit} for {property} material={polymer}",
    "{symbol}≈{value}{unit}, polymer:{polymer} recorded",
    "Reading: {value}{unit} {property} sample={polymer}",
    "Artifact {symbol}:{value}{unit}, polymer={polymer}",
    "Result: {property}={value}{unit} OCR artifact [{polymer}]",
    "Found {symbol}={value}{unit} in polymer:{polymer}",
    "Measurement: {value}{unit} {property} ({polymer})",
    "OCR Detected {symbol}={value}{unit}, polymer:{polymer}",
    "Data line: {property}={value}{unit} material:{polymer}",
    "Approximate {symbol}:{value}{unit} polymer={polymer}",
    "{value}{unit} corresponds to {property} ({polymer})",
    "Reading {symbol}:{value}{unit} material={polymer}",
    "Artifact: {property}={value}{unit}, polymer={polymer}",
    "{symbol}={value}{unit} found polymer={polymer}",
    "OCR Scan: {value}{unit} {property} polymer={polymer}",

    # Templates 1–50
    "No {property} was observed for {polymer} under test conditions.",
    "{property} could not be determined for {polymer} at {value}{unit}.",
    "The measurement failed to capture {symbol} for {polymer}.",
    "There was no significant {property} change in {polymer}.",
    "{polymer} did not exhibit measurable {property} at {value}{unit}.",
    "No evidence of {property} was found in {polymer} samples.",
    "{symbol} remained undetectable in {polymer} throughout testing.",
    "{polymer} lacks sufficient data for {property} determination.",
    "Absence of {property} signal was noted for {polymer}.",
    "No {property} could be verified for {polymer} at this stage.",
    "If {property} is below {value}{unit}, {polymer} remains stable.",
    "Unless {property} exceeds {value}{unit}, no transition occurs in {polymer}.",
    "The experiment failed to detect {symbol} in {polymer}.",
    "{property} was not recorded for {polymer} under ambient conditions.",
    "Testing revealed no discernible {property} for {polymer}.",
    "{symbol} measurement was unsuccessful for {polymer}.",
    "Without clear evidence, {property} cannot be assigned to {polymer}.",
    "{polymer} does not show {property} within {value}{unit} range.",
    "No reliable {symbol} data was obtained for {polymer}.",
    "Attempts to measure {property} failed for {polymer}.",
    "If {property} exceeds {value}{unit}, {polymer} may degrade.",
    "Unless thermal cycling is applied, {property} remains undetected in {polymer}.",
    "{polymer} showed no {property} response at {value}{unit}.",
    "The presence of {symbol} in {polymer} was inconclusive.",
    "{property} data for {polymer} was insufficient for analysis.",
    "No {property} reading was confirmed for {polymer}.",
    "If {value}{unit} is surpassed, {polymer} exhibits {property}.",
    "In the absence of catalyst, {property} was not achieved in {polymer}.",
    "No significant {property} variation was seen in {polymer} samples.",
    "{symbol} could not be detected, possibly due to instrument limitations.",
    "Failure to observe {property} suggests a stable {polymer} network.",
    "If humidity exceeds {value}{unit}, {property} changes in {polymer}.",
    "No {symbol} signals were evident in {polymer} spectra.",
    "{property} did not manifest in {polymer} during testing.",
    "{polymer} lacks measurable {property} under the given conditions.",
    "Absence of {property} response indicates no structural changes in {polymer}.",
    "Measurements suggest no detectable {symbol} for {polymer}.",
    "If {property} remains under {value}{unit}, {polymer} retains integrity.",
    "No {property} peaks were observed in the DSC trace of {polymer}.",
    "{symbol} readings were inconclusive for {polymer}.",
    "Testing at {value}{unit} yielded no {property} for {polymer}.",
    "No evidence supports {property} occurrence in {polymer}.",
    "{property} was undetectable in {polymer} throughout the experiment.",
    "If {value}{unit} threshold is crossed, {polymer} might exhibit {property}.",
    "{polymer} showed no thermal response associated with {property}.",
    "There was no detectable {symbol} activity in {polymer}.",
    "Without pressure, {property} remains absent in {polymer}.",
    "No {property} transition was seen at {value}{unit} in {polymer}.",

    # Templates 51–100
    "{polymer} failed to demonstrate {property} under thermal cycling.",
    "{symbol} could not be established for {polymer}.",
    "Attempts to determine {property} in {polymer} were unsuccessful.",
    "If {value}{unit} is not reached, {property} is absent in {polymer}.",
    "No {property} data exists for {polymer} at this temperature.",
    "The {symbol} signature was not found in {polymer}.",
    "Failure to detect {property} suggests incomplete curing of {polymer}.",
    "Inconclusive evidence for {property} in {polymer} under current tests.",
    "{polymer} lacks detectable {property} at {value}{unit}.",
    "No {property} could be measured due to sample degradation.",
    "{symbol} remained below detection limits for {polymer}.",
    "If {property} rises above {value}{unit}, {polymer} becomes unstable.",
    "Unless treated, {polymer} shows no {property} response.",
    "{property} was not found in {polymer} after multiple trials.",
    "No {property} changes were evident during heating of {polymer}.",
    "{polymer} exhibited no measurable {symbol} under standard tests.",
    "Data suggests no {property} present in {polymer}.",
    "No evidence for {symbol} peaks was found in {polymer}'s spectra.",
    "Attempts to confirm {property} yielded negative results for {polymer}.",
    "Without catalyst, {property} was not observed in {polymer}.",
    "{polymer} lacks sufficient {property} data for conclusion.",
    "If stress remains below {value}{unit}, {property} stays constant in {polymer}.",
    "No thermal transitions related to {property} were found in {polymer}.",
    "{symbol} detection was unsuccessful for {polymer}.",
    "In absence of external factors, {property} was not triggered in {polymer}.",
    "Measurement attempts of {property} failed for {polymer}.",
    "No clear {symbol} readings were recorded for {polymer}.",
    "If exposure continues, {property} may not remain stable in {polymer}.",
    "{polymer} samples showed no evidence of {property}.",
    "There were no detectable {property} signals in {polymer}.",
    "Attempts to measure {symbol} were inconclusive for {polymer}.",
    "{property} values were absent in {polymer}'s test results.",
    "Unless subjected to higher temperatures, {property} remains undetected.",
    "{polymer} revealed no {property} peaks in the analysis.",
    "No {symbol} signals were detected in {polymer} during analysis.",
    "Failure to observe {property} suggests material stability in {polymer}.",
    "{polymer} showed no evidence of {property} change post-processing.",
    "{symbol} levels were undetectable for {polymer}.",
    "If heating rate exceeds {value}{unit}, {property} emerges in {polymer}.",
    "No measurable {property} was found in {polymer} samples.",
    "{property} is absent from {polymer}'s recorded spectra.",
    "Detection of {symbol} failed for {polymer}.",
    "Without mechanical stress, no {property} was observed in {polymer}.",
    "{polymer} lacks any {property} within the measured range.",
    "If strain is below {value}{unit}, {polymer} does not show {property}.",
    "Absence of {symbol} in {polymer} suggests incomplete reaction.",
    "No measurable change in {property} was found for {polymer}.",
    "{symbol} could not be verified for {polymer} across trials.",
    "{value}{unit}",
    "Measured value: {value} {unit}",
    "Value = {value}{unit}",
    "{value} {unit} (observed)",
    "Result: {value}{unit}",
    "Recorded: {value}{unit}",
    "{value}{unit} (approximate)",
    "Value found: {value}{unit}",
    "Data: {value}{unit}",
    "{value}{unit} noted in results",
    "{value}{unit} was detected",
    "{value}{unit} observed in sample",
    "{value}{unit} reported",
    "{value}{unit} (literature)",
    "Result: {value}{unit}",
    "Peak at {value}{unit}",
    "Average: {value}{unit}",
    "Value ~ {value}{unit}",
    "Observed: {value}{unit}",
    "Approx: {value}{unit}",

    # === Symbol only ===
    "{symbol}",
    "{symbol} (detected)",
    "Symbol: {symbol}",
    "Recorded symbol: {symbol}",
    "Detected {symbol} in data",
    "Result includes {symbol}",
    "{symbol} noted",
    "Observation: {symbol}",
    "Measured: {symbol}",
    "Peak: {symbol}",

    # === Polymer only ===
    "{polymer}",
    "Material: {polymer}",
    "Tested: {polymer}",
    "Sample: {polymer}",
    "Observed in: {polymer}",
    "Recorded: {polymer}",
    "Noted: {polymer}",
    "Data entry: {polymer}",
    "Study material: {polymer}",
    "{polymer} (analyzed)",

    # === Combined but terse ===
    "{symbol} = {value}{unit}",
    "{value}{unit} for {symbol}",
    "Detected {symbol}: {value}{unit}",
    "{symbol}: {value}{unit}",
    "Result: {symbol} {value}{unit}",
    "{symbol} at {value}{unit}",
    "Approx. {symbol}: {value}{unit}",
    "Measured {symbol}: {value}{unit}",
    "Found {symbol}={value}{unit}",
    "{symbol} was {value}{unit}",

    # === Polymer + value only ===
    "{polymer}: {value}{unit}",
    "Material {polymer}, value: {value}{unit}",
    "Result for {polymer}: {value}{unit}",
    "{value}{unit} recorded for {polymer}",
    "Observed {value}{unit} in {polymer}",
    "{polymer} sample: {value}{unit}",
    "{polymer}, {value}{unit} (noted)",
    "{value}{unit} measured in {polymer}",
    "Peak value for {polymer}: {value}{unit}",
    "{polymer}: peak at {value}{unit}",

    # === Short notes, realistic OCR/table formats ===
    "Data: {symbol} = {value}{unit}",
    "Sample: {polymer}, {value}{unit}",
    "Value: {value}{unit}, Material: {polymer}",
    "{symbol} ≈ {value}{unit} (approx.)",
    "Approximate value: {value}{unit}",
    "Result table: {value}{unit}",
    "Entry: {polymer}, {value}{unit}",
    "{polymer}, {symbol}: {value}{unit}",
    "{value}{unit} ({symbol}, {polymer})",
    "{value}{unit} noted in Table 1",

    # === Minimal narrative cases ===
    "A value of {value}{unit} was reported.",
    "Observed peak at {value}{unit}.",
    "Approx. {symbol} value recorded.",
    "Resulting {symbol}: {value}{unit}.",
    "Only {symbol} noted in data.",
    "{polymer} showed no explicit {property}, but {value}{unit} was observed.",
    "{polymer} data included {value}{unit}.",
    "Recorded observation: {symbol}",
    "Inferred {property} at {value}{unit}.",
    "Estimation: {symbol} ≈ {value}{unit}",

    # === Noise & artifacts ===
    "OCR detected: {value}{unit}",
    "Scan result: {symbol}",
    "OCR artifact: {polymer}",
    "{value}{unit} (no context)",
    "u+00B0C detected in data",
    "{symbol} ~ {value}{unit} (OCR)",
    "Polymer identified: {polymer}",
    "OCR error: {symbol}={value}{unit}",
    "Artifact: {value}{unit}, {polymer}",
    "Detected noise: {symbol}",

    # === Fallback cases where property is implied ===
    "Thermal event at {value}{unit}.",
    "Transition detected: {value}{unit}.",
    "Inflection point around {value}{unit}.",
    "Onset temperature: {value}{unit}.",
    "Peak response: {symbol}",
    "Notable value: {value}{unit}.",
    "Material change observed at {value}{unit}.",
    "Shift in behavior at {value}{unit}.",
    "Approximation: {symbol}={value}{unit}",
    "Identified transition at {value}{unit}.",

    # === Literature/OCR inspired shorthand ===
    "Tg={value}{unit}",
    "σ={value}{unit}",
    "E={value}{unit}",
    "ΔH={value}{unit}",
    "k={value}{unit}",
    "ρ={value}{unit}",
    "{symbol}: {value}{unit}",
    "{symbol}={value}{unit} (lit.)",
    "{value}{unit} [{polymer}]",
    "{polymer}, {symbol}: {value}{unit}",
    "Found: {symbol}, {value}{unit}"

]

COMPLEX_TEMPLATES = [
    "The {property1} and {property2} of {polymer} were {value1} {unit1} and {value2} {unit2}, respectively.",
    "{polymer} nanocomposite showed {property1} of {value1} {unit1} while maintaining {property2} at {value2} {unit2}.",
    "Both {polymer1} and {polymer2} exhibited similar {property} values ({value1} {unit} and {value2} {unit}).",
    "The {material} containing {polymer} demonstrated {property1} = {value1} {unit1}, {property2} = {value2} {unit2}.",
]

ERROR_PATTERNS = [
    "The author {author_name} studied {polymer}.",  # Author as polymer
    "{polymer} has temperature of {value} {wrong_unit}.",  # Wrong units
    "The {non_property} was measured as {value} {unit}.",  # Non-property
]

AUTHOR_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller",
    "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez",
    "Ramprasad", "Patel", "Singh", "Kumar", "Sharma", "Verma", "Gupta",
    "Choudhury", "Das", "Roy", "Banerjee", "Mukherjee", "Saha", "Sen",
    "Chatterjee", "Bhattacharya", "Dutta", "Nath", "Bose", "Ghosh",
]

NON_PROPERTIES = [
    "color", "smell", "taste", "popularity", "cost", "availability"
]
